bot:
  token: "8474821669:AAGBkuqAcCB6JUI9SB9tvBQ9qgh3HggZRcA"
  admin_user_id: 933343496  # Your Telegram user ID for admin commands

downloads:
  output_dir: "./downloads"
  temp_dir: "./temp"
  max_file_size_mb: 50
  concurrent_downloads: 3
  cleanup_after_hours: 24

tiktok:
  quality: "best"
  format: "mp4"
  extract_audio: false

instagram:
  quality: "best"
  download_stories: true
  download_reels: true
  download_posts: true

logging:
  level: "INFO"
  file: "bot.log"
  max_file_size_mb: 10
  backup_count: 5

captions:
  include_username: true
  include_date: true
  include_platform: true
  max_length: 200
