version: '3.8'

services:
  media-downloader-bot:
    build: .
    container_name: media-downloader-bot
    restart: unless-stopped
    volumes:
      - ./downloads:/app/downloads
      - ./temp:/app/temp
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "python", "-c", "print('Bot is running')"]
      interval: 30s
      timeout: 10s
      retries: 3